### ISSUE TITLE
deserialize tx

### ISSUE THREAD

**Issue by roccomuso** [Emurgo/cardano-serialization-lib#56] opened 2020-08-21 14:08 UTC
Can you show an example using this lib to deserialize a borc encoded tx back to JSON?

**Comment by SebastienGllmt** [comment] 2020-08-26 21:48
I'm closing this since this is a duplicate of an open issue https://github.com/Emurgo/cardano-serialization-lib/issues/34

**Closed by SebastienGllmt** 2020-08-26 21:48 UTC
