### ISSUE TITLE
Can't decode address addr_test1grqe6lg9ay8wkcu5k5e38lne63c80h3nq6xxhqfmhewf645pllllllllllll7lupllllllllllll7lupllllllllllll7lc9wayvj

### ISSUE THREAD

**Issue by longngn** [Emurgo/cardano-serialization-lib#364] opened 2022-02-09 07:42 UTC
Today we stumble upon this address: `addr_test1grqe6lg9ay8wkcu5k5e38lne63c80h3nq6xxhqfmhewf645pllllllllllll7lupllllllllllll7lupllllllllllll7lc9wayvj`
This is a valid address on-chain: https://testnet.cardanoscan.io/address/40c19d7d05e90eeb6394b53313fe79d47077de33068c6b813bbe5c9d5681ffffffffffffffff7f81ffffffffffffffff7f81ffffffffffffffff7f
However, when we use `Address.from_bech32`, we get this error:
```
(node:252137) UnhandledPromiseRejectionWarning: Deserialization failed in Address.Address.Pointer.slot because: Invalid cbor: expected 32bit long unsigned integer
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by pedromtcosta** [comment] 2022-02-10 19:30
I found some strange behavior when generating pointer addresses, specifically in their hex representation. I am using the following code:
```js
const pointerAddress = PointerAddress.new(
  NetworkInfo.mainnet().network_id(),
  StakeCredential.from_keyhash(utxoPubKey.to_raw_key().hash()),
  Pointer.new(slot, txIdx, certIdx)
);
console.log('Pointer Address:    ', Buffer.from(pointerAddress.to_address().to_bytes()).toString('hex'));
```

Using the above code, when setting `slot = 0`, `txIdx = 0` and `certIdx = 0` I get the hex address `419493315cd92eb5d8c4304e67b7e16ae36d61d34502694657811a2c8e000000`. When setting `slot = 127`, `txIdx = 1` and `certIdx = 1`, the generated address in hex format is `419493315cd92eb5d8c4304e67b7e16ae36d61d34502694657811a2c8e7f0101`. Comparing the two hex addresses, we can see the only difference are the last 6 digits and that they respectively are `slot`, `txIdx` and `certIdx` converted from decimal to hexadecimal. This pattern repeats for any numbers bellow `128`, but if we use for example `slot = 128`, `txIdx = 1` and `certIdx = 1`, we get `419493315cd92eb5d8c4304e67b7e16ae36d61d34502694657811a2c8e81000101`. The last 4 digits can still be identified as `txIdx` and `certIdx`, as they are the respective hexadecimal values, but `slot` is now represented by `8100`. This in itself is not necessarily a problem, but it might be related to this issue.

**Comment by pedromtcosta** [comment] 2022-02-10 19:53
We can convert the `addr_test1grqe6lg9ay8wkcu5k5e38lne63c80h3nq6xxhqfmhewf645pllllllllllll7lupllllllllllll7lupllllllllllll7lc9wayvj` bech32 to hex using the following code:
```js
// this function was copied from the bech32 package
function convert(data, inBits, outBits, pad) {
  let value = 0;
  let bits = 0;
  const maxV = (1 << outBits) - 1;
  const result = [];
  for (let i = 0; i < data.length; ++i) {
      value = (value << inBits) | data[i];
      bits += inBits;
      while (bits >= outBits) {
          bits -= outBits;
          result.push((value >> bits) & maxV);
      }
  }
  if (pad) {
      if (bits > 0) {
          result.push((value << (outBits - bits)) & maxV);
      }
  }
  else {
      if (bits >= inBits)
          return 'Excess padding';
      if ((value << (outBits - bits)) & maxV)
          return 'Non-zero padding';
  }
  return result;
}
const decoded = bech32.decode('addr_test1grqe6lg9ay8wkcu5k5e38lne63c80h3nq6xxhqfmhewf645pllllllllllll7lupllllllllllll7lupllllllllllll7lc9wayvj', 111);
const base16 = convert(decoded.words, 5, 8, false);
const hexAddress = Buffer.from(base16);
console.log(hexAddress.toString('hex'));
```

this outputs the following value, which is the same value we can see in the URL the issue reporter posted in the first message:
```
40c19d7d05e90eeb6394b53313fe79d47077de33068c6b813bbe5c9d5681ffffffffffffffff7f81ffffffffffffffff7f81ffffffffffffffff7f
```

Comparing it with `419493315cd92eb5d8c4304e67b7e16ae36d61d34502694657811a2c8e640200` ([see my previous comment](https://github.com/Emurgo/cardano-serialization-lib/issues/364#issuecomment-1035393103)) we can see it is 54 digits bigger. If we remove these latest 54 digits, and then **replace** the latest 6 digits from the remaining number to something like `640200` (tail from the address I'm comparing to), ending up with `40c19d7d05e90eeb6394b53313fe79d47077de33068c6b813bbe5c9d56640200`, we get this hex that can be parsed using `Address.from_bytes()`.

My point here is that the error reported is probably how the Pointer is actually encoded into the address.

**Comment by rooooooooob** [comment] 2022-02-10 20:23
@pedromtcosta @longngn We deserialize the pointer part fine (I'm guessing?) as `(18446744073709551615, 18446744073709551615, 18446744073709551615)` but then when we create the pointer it fails because we only use `u32` for `Slot`, `TransactionIndex` and `CertificateIndex`.

You might be able to create this address fine but I don't see how that pointer could be valid for the staking component as those tx/cert indices are impossibly huge and such a transaction that could create them would be too big to be able to reasonably exist. Additionally, while the pointer *address* uses IOHK's variable-length natural number encoding, that is not the case for all other references of slots/tx indices.

We could potentially use our `BigInt` for those 3 fields to allow parsing of this address but the binary spec specifies `uint` (4 bytes max) for everywhere that references slots, tx indices, etc. This would be a breaking change to the API since it would change `Pointer`'s getters, and also make them incompatible with other references of slot/tx index/cert index.

So you wouldn't ever be able to use the staking component of this anywhere I think, even if the address itself is *technically* valid.

**Comment by rooooooooob** [comment] 2022-02-10 20:43
In case anyone's curious here's the part of the binary spec that is relevant:
```
; address format:
; [ 8 bit header | payload ];
;
; shelley payment addresses:
; bit 7: 0
; bit 6: base/other
; bit 5: pointer/enterprise [for base: stake cred is keyhash/scripthash]
; bit 4: payment cred is keyhash/scripthash
; bits 3-0: network id
...
; 0100: pointer address: keyhash28, 3 variable length uint
; 0101: pointer address: scripthash28, 3 variable length uint
```

While this doesn't explicitly state what the "variable length uint" format is, looking at IOHK's code for handling them gave us the typical variable length uint format where each byte is 1 bit to check if you need to move to the next byte and 7 bits to encode an actual number. There was no limit (iirc it used some bigint/natural number in haskell) specified from what I can recall. I am not sure if this was the intention though - I bet it was just an optimization for addresses more than anything to force people to use the smallest encoding since technically a 1-byte number as `uint` could be 1-4 bytes by the CBOR spec, even if every reasonable implementation would use 1 byte.

The problem is that then you have:
```
header_body =
  [
  ...
  , slot             : uint
  ...
  ]
```
and
```
transaction_index = uint
```

and

```
transaction_input = [ transaction_id : $hash32
                    , index : uint
                    ]
```

I just asked IOHK about this so depending what they'll say I can possibly put up a fix for this.

**Comment by longngn** [comment] 2022-02-11 06:43
> @pedromtcosta @longngn We deserialize the pointer part fine (I'm guessing?) as `(18446744073709551615, 18446744073709551615, 18446744073709551615)` but then when we create the pointer it fails because we only use `u32` for `Slot`, `TransactionIndex` and `CertificateIndex`.
> 
> You might be able to create this address fine but I don't see how that pointer could be valid for the staking component as those tx/cert indices are impossibly huge and such a transaction that could create them would be too big to be able to reasonably exist. Additionally, while the pointer _address_ uses IOHK's variable-length natural number encoding, that is not the case for all other references of slots/tx indices.
> 
> We could potentially use our `BigInt` for those 3 fields to allow parsing of this address but the binary spec specifies `uint` (8 bytes max) for everywhere that references slots, tx indices, etc. This would be a breaking change to the API since it would change `Pointer`'s getters, and also make them incompatible with other references of slot/tx index/cert index.
> 
> So you wouldn't ever be able to use the staking component of this anywhere I think, even if the address itself is _technically_ valid.

I agree that the stake pointer is impossibly huge and unusable. However it could be the attack vector as somebody can put such addresses in a Plutus datum for example and break all CSL decoding. So I think this issue is worth fixing.

**Comment by jmhrpr** [comment] 2022-02-13 18:41
Just stumbled on this issue, this was me - sorry! I was testing pointer addresses.

**Comment by jmhrpr** [comment] 2022-02-13 18:55
Just stumbled on this issue, this was me - sorry! I was testing pointer addresses. As you have stated, the address is valid but the staking part is useless, but the arbitrary length is definitely... strange.

**Comment by longngn** [comment] 2022-02-13 19:12
> Just stumbled on this issue, this was me - sorry! I was testing pointer addresses. As you have stated, the address is valid but the staking part is useless, but the arbitrary length is definitely... strange.

No worries, thanks to u we discovered a new bug and have a chance to improve cardano-serialization-lib ;)

**Comment by jmhrpr** [comment] 2022-03-07 22:20
@rooooooooob - sorry, just reading your comments closer
> Oops! I didn't realize that those "10 bytes" are actually only 8 bytes since they can only use 7/8 bits per byte on data and just assumed it was too big for a uint. It turns out that those indices are actually u64::max (2^64 - 1) which fits perfectly into a uint just barely.
>
>I'm guessing either:
>
>Someone wanted to test things by sticking in the max values in
It was actually -1 (no idea why though) which underflowed the uint to become 2^64 -1.

If I recall correctly, these values were only less than 2^64 because I was using the CLI or `cardano-address` which truncated the values. It was still possible to [use larger values](https://testnet.cardanoscan.io/address/addr_test1grqe6lg9ay8wkcu5k5e38lne63c80h3nq6xxhqfmhewf645pllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll7lupllllllllllll7lupllllllllllll7lcu5tw96) when doing things more manually.

**Closed** 2022-05-16 11:08 UTC
