### ISSUE TITLE
Vasil hardfork compatibility

### ISSUE THREAD

**Issue by ngua** [Emurgo/cardano-serialization-lib#437] opened 2022-05-18 04:59 UTC
Apologies if I've missed anything, but do you have plans to upgrade the library after the Vasil hardfork? I looked through the issues and milestones but didn't see anything related to this

Thanks!

**Comment by 0xtrossets** [comment] 2022-05-30 05:14
I'm also curious about this.

**Comment by rooooooooob** [comment] 2022-05-31 00:48
@0xtrossets @ngua  I can't say what kind of plans Emurgo has, but I can tell you that unless you plan on using the new features the binary(CBOR) produced by cardano-serialization-lib is, with the exception of block header bodies, is binary backwards compatible with the hardfork. I think almost no one is using that part of this lib anyway unless they're using it to read chain data raw. So you can use this lib to create transactions/etc as long as you don't need support for collateral returns/total returns/reference inputs/inline datums/etc. Parsing on-chain data will fail since there are extra CBOR fields that didn't exist in Alonzo though.

**Comment by danbigthink** [comment] 2022-06-22 19:27
I've seen an alpha version 11 kicking around

**Comment by vsubhuman** [comment] 2022-06-22 21:09
There's a beta release available now with all the changes added, you can check the details here: https://github.com/Emurgo/cardano-serialization-lib/pull/463

It will be released as major version 11, once we have everything tested and confirmed

**Comment by vsubhuman** [comment] 2022-07-27 13:15
https://github.com/Emurgo/cardano-serialization-lib/releases/tag/11.0.0

**Closed by vsubhuman** 2022-07-27 13:15 UTC
Labels: babbage
