### ISSUE TITLE
PlutusList array serialization is different from cardano-cli

### ISSUE THREAD

**Issue by kodemill** [Emurgo/cardano-serialization-lib#227] opened 2021-10-22 17:21 UTC
Currently this library uses the **fixed-length array** CBOR type to serialize the `PlutusList` data type, whereas from what we've observed the cardano-cli encodes the datum as [**indefinite-length array**](https://www.rfc-editor.org/rfc/rfc8949.html#name-indefinite-length-arrays-an) with some exceptions:

- an empty array is encoded as fixed (zero) length array
- the root level PlutusList in the TransactionWitnessSet is encoded as a fixed length array

An example hex-encoded cbor of a datum generated by the cli:
`d8799f4100d8799fd8799fd8799f581cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd8799fd8799fd8799f581cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd87a80ff1a002625a0d8799fd879801a000f4240d87a80ffff`
Decoding and then re-encoding the above datum using `PlutusData` from this lib will result in the following:
`d879844100d87982d87982d87981581cffffffffffffffffffffffffffffffffffffffffffffffffffffffffd87981d87981d87981581cffffffffffffffffffffffffffffffffffffffffffffffffffffffffd87a801a002625a0d87983d879801a000f4240d87a80`

This minor inconsistency between these core tools might cause some problems for the ecosystem developers. I'd be happy to provide a PR to fix this.

As an example, when a wallet signs a transaction and hands it back, the hash of the datum is different, leading to `NonOutputSupplimentaryDatums` errors when submitting the transaction.

**Comment by JaredCorduan** [comment] 2021-10-29 18:53
thank you @kodemill . I'll make a link here to the ledger issue: https://github.com/input-output-hk/cardano-ledger-specs/issues/2512

**Comment by rooooooooob** [comment] 2021-11-24 01:39
Closing due to #228 being merged.

**Closed by rooooooooob** 2021-11-24 01:39 UTC

**Comment by mailtodanish** [comment] 2022-01-10 15:45
We generate datum script using below :

cardano-cli transaction hash-script-data --script-data-file ${datum_name}.datum

It generates the datum script. once we have datum we need to incluide it into transaction 
that is generated on cli again


 cardano-cli transaction build \
                --alonzo-era \
                --tx-in ${utxoin} \
                --tx-out ${SCRIPT_ADDR}+${LOCK_AMNT} \
                --tx-out-datum-hash ${hashes[0]} \
                --metadata-json-file metadata.json \
				
Please let me know how to do above datum using nami-wallet-api or

cardano-serialization-lib-browser ? any reference

**Comment by AdamMachera** [comment] 2022-05-17 08:12
Currently we are using cardano-serialization-lib in version 9.1.4 with Alessandro adjustments

We have following code to 

```
export const toPlutusData = (plutusDataObj: PlutusDataObject) => {
    const datumFields = PlutusList.new();
    plutusDataObj.fields.sort((a, b) => a.index - b.index);
    plutusDataObj.fields.forEach(f => {
        switch (f.type) {
            case PlutusFieldType.Integer:
                datumFields.add(PlutusData.new_integer(BigInt.from_str(f.value.toString())));
                break;
            case PlutusFieldType.Data:
                datumFields.add(toPlutusData(f.value));
                break;
            case PlutusFieldType.Bytes:
                datumFields.add(PlutusData.new_bytes(f.value));
                break;
        }
    })

    return PlutusData.new_constr_plutus_data(
        ConstrPlutusData.new(
            Int.new_i32(plutusDataObj.constructorIndex),
            datumFields
        )
    );
}

    const someDatum = createSomeDatum(pkh, someParams);
    const someDatumHash = hash_plutus_data(toPlutusData(someDatum));
    const contractOutput = TransactionOutput.new(
        getContractAddress(),
        getContractOutput(amount.toString(), someParams)
    );

    contractOutput.set_data_hash(someDatumHash);

```

Currently we are aware that using cardano-cli we cannot "withdraw" from smart contract because version 9.1.4 computes differently hash.
If we move to version 10.0.0.x cardano-serialization-lib we are going to be able to withdraw funds from smart contract using cardano-cli because both products compute hash the same way.

The problem is that we have scenario that user locked his NFT in marketplace smartcontract using cardano-serialization-lib 9.1.4.
When we migrate to cardano-serialization-lib 10.0.0.5 user won't be able to cancel his/her offering because datum hash is going to be computed in right way that is not backward compatible with locking token operation.

To be backward compatible I think that there should be overload to hash_plutus_data
const isFiniteArray = true
hash_plutus_data(toPlutusData(someDatum), isFiniteArray);

so we can allow old tokens that are locked in smart contract with cardano-serialization-lib in version 9.1.4 to be able to be withdrawn.
