### ISSUE TITLE
Empty asset names

### ISSUE THREAD

**Issue by zxpectre** [Emurgo/cardano-serialization-lib#171] opened 2021-06-24 19:18 UTC
I'm having issues dealing with tokens like the testnet faucet's "Testcoin", which have zero length asset names.

```
let assetName="";
AssetName.new(Buffer.from(assetName, 'hex'));
...
```
How should I treat them to avoid this error further in code:
`Deserialization: Invalid cbor: not enough bytes, expect 0 bytes but received 0 bytes.`

Thanks.

**Comment by rooooooooob** [comment] 2021-07-17 02:20
@zxpectre Do those 2 lines of code error for you? If so, which version are you using?

I just quickly tried:

```rust
let asset_name = AssetName::new(vec![]).unwrap();
let deser = AssetName::from_bytes(asset_name.to_bytes()).unwrap();
```

from rust since I had those open and didn't have the wasm bindings built or set up to test

**Comment by rooooooooob** [comment] 2021-12-16 03:07
Closing this because no one has reported any problems since and I couldn't reproduce it in rust before and can't produce it on `master` from wasm either now using the code posted by OP directly.

**Closed by rooooooooob** 2021-12-16 03:07 UTC

**Comment by 0xtrossets** [comment] 2022-08-02 22:25
Seeing this issue also.
@zxpectre did you find a solution to it?

**Comment by wutzebaer** [comment] 2024-03-07 19:53
> Seeing this issue also. @zxpectre did you find a solution to it?

this works for me even with empty strings:

`const assetName = AssetName.new(Buffer.from(token.maName, 'hex'));`
