### ISSUE TITLE
Failed to deserialize PlutusData encoded using Plutus Haskell SDK

### ISSUE THREAD

**Issue by oskin1** [Emurgo/cardano-serialization-lib#302] opened 2021-12-21 11:08 UTC
I'm trying to make a roundtrip serialization
In Haskell I'm creating a simple datum and trying to deserialize it on serlib side
Haskell:
```haskell
import qualified Codec.Serialise as S
prettyPrint $ BL.toStrict $ S.serialise $ Datum (toBuiltinData myDatum) where myDatum = SomeDatum {a = 10, b = 2}
```
Output:
```
"d8799fa2ff"
```
In JS code:
```typescript
RustModule.CardanoWasm.PlutusData.from_bytes(decodeHex("d8799fa2ff"))
```
Output:
```
Rejected promise returned by test. Reason:

  'Deserialization failed in PlutusDataEnum.PlutusDataEnum because: No variant matched'
```

"@emurgo/cardano-serialization-lib-browser": "10.0.0-beta.8"

**Comment by vsubhuman** [comment] 2021-12-27 11:53
@ernestocoinweb @twwu123 , can you guys plz look into that Haskell part. I am not sure about the serialisation details there yet, but `d8799fa2ff` really looks like it's way too short to encode a datum like `{a = 10, b = 2}` 🤔

**Comment by rooooooooob** [comment] 2021-12-28 09:15
@oskin1 The CBOR does not appear to be valid.

`d879` - tag(121)
`9f`- arr(indefinite)
`a2` - map(len 2)
`ff` - break

It looks like it was meant to be a tagged alternative using variant 0 tagging a single map but then it's missing its keys/values. I'm guessing it was supposed to have 2 keys/values being `STR(a) => UINT(10)` and `STR(b) => UINT(2)` like your input but they're simply missing.

**Comment by rooooooooob** [comment] 2022-01-20 05:54
I'm closing this issue for now as it seems like the issue is in whereever the CBOR was being generated, and not in this library.

**Closed by rooooooooob** 2022-01-20 05:54 UTC
