### ISSUE TITLE
can't access lexical declaration 'Bip32PrivateKey' before initialization with Webpack5 and browser version

### ISSUE THREAD

**Issue by refi93** [Emurgo/cardano-serialization-lib#166] opened 2021-06-11 15:55 UTC
We are trying to use the browser version of the library in a project built with webpack5 (with `experiments.asyncWebAssembly = true`) and calls to the library are failing with errors like:

```
can't access lexical declaration 'Bip32PrivateKey' before initialization
```

Interestingly, when we rebuilt the library locally from source with `npm rust:build-browser`, this version didn't have the problem. We have a suspicion it's related to this: https://github.com/rustwasm/wasm-bindgen/issues/2343 - so probably republishing the lib with the latest wasm building tooling is the solution to this problem

We don't have a minimum repro of this issue, but given that issue the explanation seems plausible

**Comment by SebastienGllmt** [comment] 2021-06-11 16:01
Interesting. I've used the package successfully in Webpack5 with `asyncWebAssembly: true` so I'm not sure what could be causing the issue for you, but the published version of this library used a fairly old version of bindgen since we were blocked from upgrading it due to another issue. The issue was recently fixed so we bumped the bindgen version on Github but never re-deployed

**Comment by refi93** [comment] 2021-06-11 16:50
the version built locally was based on https://github.com/Emurgo/cardano-serialization-lib/commit/26c262021c2c77554c9c804f838bbab23539065e - so it can indeed have something to do with the bindgen update

**Comment by SebastienGllmt** [comment] 2021-06-11 22:19
Okay, I think I managed to reproduce your issue and confirmed that 7.1.0 that I just pushed fixed this. Feel free to re-open the issue if you still run into this problem 👍

**Closed by SebastienGllmt** 2021-06-11 22:19 UTC
